import React from 'react';
import firebase from "firebase";

/*
CACHE FIRST APPROACH
AVOID TOO MANY CALLS TO FINNHUB, PROVOQUING BREACHING THE FREE TIER
TIER: 60 CALLS PER MINUTE

ADDED LIMITATIONS:
POSITION 1 CALL PER MINUTE PER STOCK
NEW 1 CALL PER 5 MINUTES PER STOCK

CACHE: FIREBASE - 50K READS DAY
*/


/* TO BE APPLIED TO:
STOCK.JS
STOCKPOSITION.JS
*/
